### ISSUE TITLE
Linkswap concept and mock-ups

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/Product-Feedback#3]
# Description

We have discussed a lot about the possibility of extending Linkdrop and Linkdro PRO with Linkswap functionality

# Subtasks included

- [ ] Write up technical description
- [x] Make different conceptual mock-ups comparing UX
- [ ] Research if and how this is different than https://boxswap.io/
- [ ] Research if and how this provides synergy to https://0x.org/
