### ISSUE TITLE
Integrate analytics

### ISSUE THREAD

**Issue by seichris** [LinkdropProtocol/Product-Feedback#4]
Come up with a simple approach to get anonymized user data for sender & receiver.

Sender & Receiver:
- Does he have ETH?
- Location, referral, source?
- mobile/desktop?
- user who comes back?
- ethereum address?

## Tasks

- [ ] Research simple integration
- [ ] Research simple UI
- [ ] Research simple export
